/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ddv.test.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SecurityTrade extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2527720136242601236L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SecurityTrade\",\"namespace\":\"com.ddv.test.avro\",\"fields\":[{\"name\":\"securityname\",\"type\":\"string\"},{\"name\":\"details\",\"type\":{\"type\":\"record\",\"name\":\"CommonDetails\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"favorite_number\",\"type\":[\"int\",\"null\"]},{\"name\":\"favorite_color\",\"type\":[\"string\",\"null\"]}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SecurityTrade> ENCODER =
      new BinaryMessageEncoder<SecurityTrade>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SecurityTrade> DECODER =
      new BinaryMessageDecoder<SecurityTrade>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SecurityTrade> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SecurityTrade> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SecurityTrade> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SecurityTrade>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SecurityTrade to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SecurityTrade from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SecurityTrade instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SecurityTrade fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence securityname;
   private com.ddv.test.avro.CommonDetails details;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SecurityTrade() {}

  /**
   * All-args constructor.
   * @param securityname The new value for securityname
   * @param details The new value for details
   */
  public SecurityTrade(java.lang.CharSequence securityname, com.ddv.test.avro.CommonDetails details) {
    this.securityname = securityname;
    this.details = details;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return securityname;
    case 1: return details;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: securityname = (java.lang.CharSequence)value$; break;
    case 1: details = (com.ddv.test.avro.CommonDetails)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'securityname' field.
   * @return The value of the 'securityname' field.
   */
  public java.lang.CharSequence getSecurityname() {
    return securityname;
  }


  /**
   * Sets the value of the 'securityname' field.
   * @param value the value to set.
   */
  public void setSecurityname(java.lang.CharSequence value) {
    this.securityname = value;
  }

  /**
   * Gets the value of the 'details' field.
   * @return The value of the 'details' field.
   */
  public com.ddv.test.avro.CommonDetails getDetails() {
    return details;
  }


  /**
   * Sets the value of the 'details' field.
   * @param value the value to set.
   */
  public void setDetails(com.ddv.test.avro.CommonDetails value) {
    this.details = value;
  }

  /**
   * Creates a new SecurityTrade RecordBuilder.
   * @return A new SecurityTrade RecordBuilder
   */
  public static com.ddv.test.avro.SecurityTrade.Builder newBuilder() {
    return new com.ddv.test.avro.SecurityTrade.Builder();
  }

  /**
   * Creates a new SecurityTrade RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SecurityTrade RecordBuilder
   */
  public static com.ddv.test.avro.SecurityTrade.Builder newBuilder(com.ddv.test.avro.SecurityTrade.Builder other) {
    if (other == null) {
      return new com.ddv.test.avro.SecurityTrade.Builder();
    } else {
      return new com.ddv.test.avro.SecurityTrade.Builder(other);
    }
  }

  /**
   * Creates a new SecurityTrade RecordBuilder by copying an existing SecurityTrade instance.
   * @param other The existing instance to copy.
   * @return A new SecurityTrade RecordBuilder
   */
  public static com.ddv.test.avro.SecurityTrade.Builder newBuilder(com.ddv.test.avro.SecurityTrade other) {
    if (other == null) {
      return new com.ddv.test.avro.SecurityTrade.Builder();
    } else {
      return new com.ddv.test.avro.SecurityTrade.Builder(other);
    }
  }

  /**
   * RecordBuilder for SecurityTrade instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SecurityTrade>
    implements org.apache.avro.data.RecordBuilder<SecurityTrade> {

    private java.lang.CharSequence securityname;
    private com.ddv.test.avro.CommonDetails details;
    private com.ddv.test.avro.CommonDetails.Builder detailsBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ddv.test.avro.SecurityTrade.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.securityname)) {
        this.securityname = data().deepCopy(fields()[0].schema(), other.securityname);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.details)) {
        this.details = data().deepCopy(fields()[1].schema(), other.details);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasDetailsBuilder()) {
        this.detailsBuilder = com.ddv.test.avro.CommonDetails.newBuilder(other.getDetailsBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing SecurityTrade instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ddv.test.avro.SecurityTrade other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.securityname)) {
        this.securityname = data().deepCopy(fields()[0].schema(), other.securityname);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.details)) {
        this.details = data().deepCopy(fields()[1].schema(), other.details);
        fieldSetFlags()[1] = true;
      }
      this.detailsBuilder = null;
    }

    /**
      * Gets the value of the 'securityname' field.
      * @return The value.
      */
    public java.lang.CharSequence getSecurityname() {
      return securityname;
    }


    /**
      * Sets the value of the 'securityname' field.
      * @param value The value of 'securityname'.
      * @return This builder.
      */
    public com.ddv.test.avro.SecurityTrade.Builder setSecurityname(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.securityname = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'securityname' field has been set.
      * @return True if the 'securityname' field has been set, false otherwise.
      */
    public boolean hasSecurityname() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'securityname' field.
      * @return This builder.
      */
    public com.ddv.test.avro.SecurityTrade.Builder clearSecurityname() {
      securityname = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'details' field.
      * @return The value.
      */
    public com.ddv.test.avro.CommonDetails getDetails() {
      return details;
    }


    /**
      * Sets the value of the 'details' field.
      * @param value The value of 'details'.
      * @return This builder.
      */
    public com.ddv.test.avro.SecurityTrade.Builder setDetails(com.ddv.test.avro.CommonDetails value) {
      validate(fields()[1], value);
      this.detailsBuilder = null;
      this.details = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'details' field has been set.
      * @return True if the 'details' field has been set, false otherwise.
      */
    public boolean hasDetails() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'details' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.ddv.test.avro.CommonDetails.Builder getDetailsBuilder() {
      if (detailsBuilder == null) {
        if (hasDetails()) {
          setDetailsBuilder(com.ddv.test.avro.CommonDetails.newBuilder(details));
        } else {
          setDetailsBuilder(com.ddv.test.avro.CommonDetails.newBuilder());
        }
      }
      return detailsBuilder;
    }

    /**
     * Sets the Builder instance for the 'details' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.ddv.test.avro.SecurityTrade.Builder setDetailsBuilder(com.ddv.test.avro.CommonDetails.Builder value) {
      clearDetails();
      detailsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'details' field has an active Builder instance
     * @return True if the 'details' field has an active Builder instance
     */
    public boolean hasDetailsBuilder() {
      return detailsBuilder != null;
    }

    /**
      * Clears the value of the 'details' field.
      * @return This builder.
      */
    public com.ddv.test.avro.SecurityTrade.Builder clearDetails() {
      details = null;
      detailsBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SecurityTrade build() {
      try {
        SecurityTrade record = new SecurityTrade();
        record.securityname = fieldSetFlags()[0] ? this.securityname : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (detailsBuilder != null) {
          try {
            record.details = this.detailsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("details"));
            throw e;
          }
        } else {
          record.details = fieldSetFlags()[1] ? this.details : (com.ddv.test.avro.CommonDetails) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SecurityTrade>
    WRITER$ = (org.apache.avro.io.DatumWriter<SecurityTrade>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SecurityTrade>
    READER$ = (org.apache.avro.io.DatumReader<SecurityTrade>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.securityname);

    this.details.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.securityname = in.readString(this.securityname instanceof Utf8 ? (Utf8)this.securityname : null);

      if (this.details == null) {
        this.details = new com.ddv.test.avro.CommonDetails();
      }
      this.details.customDecode(in);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.securityname = in.readString(this.securityname instanceof Utf8 ? (Utf8)this.securityname : null);
          break;

        case 1:
          if (this.details == null) {
            this.details = new com.ddv.test.avro.CommonDetails();
          }
          this.details.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










